import {Property} from '../Property.model';

const list = [
    'England',
    'Scotland',
    'Ireland',
    'France',
    'Germany',
    'Italy',
    'Europe',
    'Crusades',
    'Africa',
    'India',
    'China',
    'Jigsaw',
    'Rose',
    'Bullseye',
    'Crossroads',
    'Rorschach',
    'Centreville',
    'Quaintville',
    'Pretzelland',
    'N. England',
    'Equalizer',
    'RubixWorld',
    'Pentagon',
    'YinYang',
    'map no 25',
    'map no 26',
    'map no 27',
    'map no 28',
    'map no 29',
    'map no 30',
    'map no 31',
    'map no 32',
    'map no 33',
    'map no 34',
    'map no 35',
    'map no 36',
    'map no 37',
    'map no 38',
    'map no 39',
    'map no 40',
    'Britain Imperium',
    'The World',
    'Japan',
    'U.S.A.',
    'S. America',
    'Butterfly',
    'Deadlock',
    'Torus',
    'Vortex',
    'Patches',
    'The Snake',
    'Australia',
    'Central Am.',
    'Waterworld',
    'The Hub',
    'Roundabout',
    'Knotsville',
    'Cubium',
    'Snowflake'
];

export class Name extends Property {

    get label() {
        return list[this.value];
    }
}